name: Next.js CI build

on:
  pull_request:
    branches: 
      - production
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Install dependencies
        run: npm install

      #- name: Run unit tests
      #  run: npm run test

      - name: Build
        run: npm run build